import type { Booking, Course } from './types';

/**
 * Built-in demo data. Used as a graceful fallback for the public site
 * whenever Supabase env vars are not configured, so the UI is fully
 * browseable during development. Dates are forward-looking from mid-2026.
 *
 * This same content is inserted as seed rows by supabase/seed.sql.
 */
export const MOCK_COURSES: Course[] = [
  {
    id: 'demo-ds-london-jul',
    title: 'SIA Door Supervision: Level 2 Award',
    course_type: 'door_supervision',
    description:
      'Our flagship 6-day Door Supervisor course delivers everything you need to apply for your SIA licence: physical intervention, conflict management, and the law, taught by working professionals.',
    start_date: '2026-07-13',
    end_date: '2026-07-18',
    start_time: '09:00',
    end_time: '17:00',
    location: 'London, Stratford Training Centre',
    price: 249,
    max_spaces: 16,
    available_spaces: 5,
    image_url: null,
    status: 'published',
    created_at: '2026-05-01T09:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 'demo-cp-london-jul',
    title: 'SIA Close Protection: Level 3 Award',
    course_type: 'close_protection',
    description:
      'An intensive 14-day Close Protection programme covering operational planning, foot and vehicle drills, threat assessment and professional conduct, the standard required to work as a CPO.',
    start_date: '2026-07-20',
    end_date: '2026-08-02',
    start_time: '08:30',
    end_time: '18:00',
    location: 'London, Stratford Training Centre',
    price: 1895,
    max_spaces: 12,
    available_spaces: 3,
    image_url: null,
    status: 'published',
    created_at: '2026-05-01T09:00:00Z',
    updated_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 'demo-ds-birmingham-aug',
    title: 'SIA Door Supervision: Level 2 Award',
    course_type: 'door_supervision',
    description:
      'The complete Door Supervisor qualification delivered over six days in central Birmingham. Small group sizes, experienced trainers and full exam support included.',
    start_date: '2026-08-10',
    end_date: '2026-08-15',
    start_time: '09:00',
    end_time: '17:00',
    location: 'Birmingham, City Centre Venue',
    price: 239,
    max_spaces: 16,
    available_spaces: 11,
    image_url: null,
    status: 'published',
    created_at: '2026-05-12T09:00:00Z',
    updated_at: '2026-05-12T09:00:00Z',
  },
  {
    id: 'demo-ds-london-aug',
    title: 'SIA Door Supervision: Level 2 Award (Weekend Friendly)',
    course_type: 'door_supervision',
    description:
      'Same comprehensive Door Supervisor qualification, scheduled across two weeks to suit those balancing work commitments. Includes first aid and physical intervention modules.',
    start_date: '2026-08-24',
    end_date: '2026-08-29',
    start_time: '09:00',
    end_time: '17:00',
    location: 'London, Stratford Training Centre',
    price: 249,
    max_spaces: 16,
    available_spaces: 16,
    image_url: null,
    status: 'published',
    created_at: '2026-05-20T09:00:00Z',
    updated_at: '2026-05-20T09:00:00Z',
  },
  {
    id: 'demo-cp-manchester-sep',
    title: 'SIA Close Protection: Level 3 Award',
    course_type: 'close_protection',
    description:
      'Our Close Protection course returns to Manchester. Build the operational skillset and professional standards expected of a modern Close Protection Officer across a focused 15-day programme.',
    start_date: '2026-09-07',
    end_date: '2026-09-21',
    start_time: '08:30',
    end_time: '18:00',
    location: 'Manchester, Training Academy',
    price: 1850,
    max_spaces: 12,
    available_spaces: 9,
    image_url: null,
    status: 'published',
    created_at: '2026-06-02T09:00:00Z',
    updated_at: '2026-06-02T09:00:00Z',
  },
  {
    id: 'demo-ds-london-sep',
    title: 'SIA Door Supervision: Level 2 Award',
    course_type: 'door_supervision',
    description:
      'Start your security career this autumn. A complete six-day Door Supervisor qualification with full SIA licence application support on completion.',
    start_date: '2026-09-14',
    end_date: '2026-09-19',
    start_time: '09:00',
    end_time: '17:00',
    location: 'London, Stratford Training Centre',
    price: 249,
    max_spaces: 16,
    available_spaces: 14,
    image_url: null,
    status: 'published',
    created_at: '2026-06-10T09:00:00Z',
    updated_at: '2026-06-10T09:00:00Z',
  },
];

/** Demo bookings — only ever shown in the admin portal fallback view. */
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'demo-booking-1',
    course_id: 'demo-ds-london-jul',
    customer_name: 'James Okafor',
    customer_email: 'james.okafor@example.com',
    customer_phone: '07700 900123',
    message: 'Looking to start working events this summer. Do I need to bring ID?',
    booking_status: 'new',
    created_at: '2026-06-21T14:05:00Z',
    updated_at: '2026-06-21T14:05:00Z',
    course: {
      id: 'demo-ds-london-jul',
      title: 'SIA Door Supervision: Level 2 Award',
      course_type: 'door_supervision',
      start_date: '2026-07-13',
    },
  },
  {
    id: 'demo-booking-2',
    course_id: 'demo-cp-london-jul',
    customer_name: 'Sofia Marenko',
    customer_email: 'sofia.m@example.com',
    customer_phone: '07700 900456',
    message: 'Ex-military, transitioning into the private sector. Preferred start 20 July.',
    booking_status: 'confirmed',
    created_at: '2026-06-18T09:42:00Z',
    updated_at: '2026-06-19T11:00:00Z',
    course: {
      id: 'demo-cp-london-jul',
      title: 'SIA Close Protection: Level 3 Award',
      course_type: 'close_protection',
      start_date: '2026-07-20',
    },
  },
  {
    id: 'demo-booking-3',
    course_id: 'demo-ds-birmingham-aug',
    customer_name: 'Daniel Price',
    customer_email: 'd.price@example.com',
    customer_phone: '07700 900789',
    message: null,
    booking_status: 'new',
    created_at: '2026-06-25T16:20:00Z',
    updated_at: '2026-06-25T16:20:00Z',
    course: {
      id: 'demo-ds-birmingham-aug',
      title: 'SIA Door Supervision: Level 2 Award',
      course_type: 'door_supervision',
      start_date: '2026-08-10',
    },
  },
];
